;; OHOS_LOCAL begin
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: ark_gc_support
; RUN: llc --mtriple=loongarch64 --mattr=+d < %s | FileCheck %s

;; Test that prolog/epilog are generated when ghc call webkit because we need to push regs to stack.

define ghccc void @caller(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: caller:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi.d $sp, $sp, -16
; CHECK-NEXT:    move $a0, $s0
; CHECK-NEXT:    st.d $fp, $sp, 0
; CHECK-NEXT:    bl %plt(callee)
; CHECK-NEXT:    addi.d $sp, $sp, 16
; CHECK-NEXT:    ret
  call webkit_jscc void @callee(i64 %a, i64 %b)
  ret void
}

declare void @callee(i64, i64)
;; OHOS_LOCAL end
