;; OHOS_LOCAL begin
; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; REQUIRES: ark_gc_support
; RUN: llc --mtriple=loongarch64 --mattr=+d < %s | FileCheck %s

;; 32-bit integers are only aligned to 4 bytes, even on loongarch64.
;; They are *not* promoted to i64.
define webkit_jscc i32 @simple_jscall(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: simple_jscall:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.w $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ld.w $a1, $sp, 8
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i32 %a, %b
  %abc = add i32 %ab, %c
  ret i32 %abc
}

define webkit_jscc i1 @test_i1(i1 %a, i1 %b) {
; CHECK-LABEL: test_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.d $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i1 %a, %b
  ret i1 %ab
}

define webkit_jscc i8 @test_i8(i8 %a, i8 %b) {
; CHECK-LABEL: test_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.b $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i8 %a, %b
  ret i8 %ab
}

define webkit_jscc i16 @test_i16(i16 %a, i16 %b) {
; CHECK-LABEL: test_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.h $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i16 %a, %b
  ret i16 %ab
}

define webkit_jscc i32 @test_i32(i32 %a, i32 %b) {
; CHECK-LABEL: test_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.w $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i32 %a, %b
  ret i32 %ab
}

define webkit_jscc i64 @test_i64(i64 %a, i64 %b) {
; CHECK-LABEL: test_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld.d $a1, $sp, 0
; CHECK-NEXT:    add.d $a0, $a0, $a1
; CHECK-NEXT:    ret
  %ab = add i64 %a, %b
  ret i64 %ab
}

define webkit_jscc float @test_float(float %a, float %b) {
; CHECK-LABEL: test_float:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fld.s $fa0, $sp, 4
; CHECK-NEXT:    fld.s $fa1, $sp, 0
; CHECK-NEXT:    fadd.s $fa0, $fa1, $fa0
; CHECK-NEXT:    ret
  %ab = fadd float %a, %b
  ret float %ab
}

define webkit_jscc double @test_double(double %a, double %b) {
; CHECK-LABEL: test_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fld.d $fa0, $sp, 8
; CHECK-NEXT:    fld.d $fa1, $sp, 0
; CHECK-NEXT:    fadd.d $fa0, $fa1, $fa0
; CHECK-NEXT:    ret
  %ab = fadd double %a, %b
  ret double %ab
}
;; OHOS_LOCAL end
