; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    -verify-machineinstrs \
; RUN:   -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefixes=UNCHECKED-ELF
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                     -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:   -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefixes=UNCHECKED-ELF

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    -verify-machineinstrs \
; RUN:   -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL="L" --check-prefixes=UNCHECKED-HINT
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:   -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL="L" --check-prefixes=UNCHECKED-HINT


; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    -verify-machineinstrs \
; RUN:                                     | FileCheck %s -DL=".L" --check-prefixes=CHECKED-ELF
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:                                     | FileCheck %s -DL=".L" --check-prefixes=CHECKED-ELF

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    -verify-machineinstrs \
; RUN:                                     | FileCheck %s -DL=".L" --check-prefixes=CHECKED-HINT
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:                                     | FileCheck %s -DL=".L" --check-prefixes=CHECKED-HINT


; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    -verify-machineinstrs \
; RUN:   -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefixes=TRAP-ELF
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:   -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefixes=TRAP-ELF

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    -verify-machineinstrs \
; RUN:   -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefixes=TRAP-HINT
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 -verify-machineinstrs \
; RUN-NOT:   -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefixes=TRAP-HINT

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"

define i64 @test_auth_blend(i64 %arg, i64 %arg1) {
; UNCHECKED-ELF-LABEL: test_auth_blend:
; UNCHECKED-ELF:       %bb.0:
; UNCHECKED-ELF-NEXT:    movk x1, #65535, lsl #48
; UNCHECKED-ELF-NEXT:    autda x0, x1
; UNCHECKED-ELF-NEXT:    ret
;
; UNCHECKED-HINT-LABEL: test_auth_blend:
; UNCHECKED-HINT:       %bb.0:
; UNCHECKED-HINT-NEXT:    mov x17, x0
; UNCHECKED-HINT-NEXT:    mov x16, x1
; UNCHECKED-HINT-NEXT:    movk x16, #65535, lsl #48
; UNCHECKED-HINT-NEXT:    autia1716
; UNCHECKED-HINT-NEXT:    mov x0, x17
; UNCHECKED-HINT-NEXT:    ret
;
; CHECKED-ELF-LABEL: test_auth_blend:
; CHECKED-ELF:       %bb.0:
; CHECKED-ELF-NEXT:    movk x1, #65535, lsl #48
; CHECKED-ELF-NEXT:    autda x0, x1
; CHECKED-ELF-NEXT:    ret
;
; CHECKED-HINT-LABEL: test_auth_blend:
; CHECKED-HINT:       %bb.0:
; CHECKED-HINT-NEXT:    mov x17, x0
; CHECKED-HINT-NEXT:    mov x16, x1
; CHECKED-HINT-NEXT:    movk x16, #65535, lsl #48
; CHECKED-HINT-NEXT:    autia1716
; CHECKED-HINT-NEXT:    mov x0, x17
; CHECKED-HINT-NEXT:    ret
;
; TRAP-ELF-LABEL: test_auth_blend:
; TRAP-ELF:       %bb.0:
; TRAP-ELF-NEXT:    movk x1, #65535, lsl #48
; TRAP-ELF-NEXT:    autda x0, x1
; TRAP-ELF-NEXT:    mov x8, x0
; TRAP-ELF-NEXT:    xpacd x8
; TRAP-ELF-NEXT:    cmp x8, x0
; TRAP-ELF-NEXT:    b.eq [[L]]auth_success_0
; TRAP-ELF-NEXT:    brk #0xc472
; TRAP-ELF-NEXT:  Lauth_success_0:
; TRAP-ELF-NEXT:    ret
;
; TRAP-HINT-LABEL: test_auth_blend:
; TRAP-HINT:       %bb.0:
; TRAP-HINT-NEXT:    mov x17, x0
; TRAP-HINT-NEXT:    mov x16, x1
; TRAP-HINT-NEXT:    movk x16, #65535, lsl #48
; TRAP-HINT-NEXT:    autia1716
; TRAP-HINT-NEXT:    mov x16, x17
; TRAP-HINT-NEXT:    xpacd x16
; TRAP-HINT-NEXT:    cmp x16, x17
; TRAP-HINT-NEXT:    b.eq [[L]]auth_success_0
; TRAP-HINT-NEXT:    brk #0xc472
; TRAP-HINT-NEXT:  Lauth_success_0:
; TRAP-HINT-NEXT:    mov x0, x17
; TRAP-HINT-NEXT:    ret
  %tmp0 = call i64 @llvm.ptrauth.blend(i64 %arg1, i64 65535)
  %tmp1 = call i64 @llvm.ptrauth.auth(i64 %arg, i32 2, i64 %tmp0)
  ret i64 %tmp1
}

define i64 @test_resign_blend(i64 %arg, i64 %arg1, i64 %arg2) {
; UNCHECKED-ELF-LABEL: test_resign_blend:
; UNCHECKED-ELF:       %bb.0:
; UNCHECKED-ELF-NEXT:    mov x17, x0
; UNCHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; UNCHECKED-ELF-NEXT:    autda x17, x1
; UNCHECKED-ELF-NEXT:    mov x16, x2
; UNCHECKED-ELF-NEXT:    movk x16, #56789, lsl #48
; UNCHECKED-ELF-NEXT:    pacdb x17, x16
; UNCHECKED-ELF-NEXT:    mov x0, x17
; UNCHECKED-ELF-NEXT:    ret
;
; UNCHECKED-HINT-LABEL: test_resign_blend:
; UNCHECKED-HINT:       %bb.0:
; UNCHECKED-HINT-NEXT:    mov x17, x0
; UNCHECKED-HINT-NEXT:    mov x16, x1
; UNCHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; UNCHECKED-HINT-NEXT:    autia1716
; UNCHECKED-HINT-NEXT:    mov x16, x2
; UNCHECKED-HINT-NEXT:    movk x16, #56789, lsl #48
; UNCHECKED-HINT-NEXT:    pacib1716
; UNCHECKED-HINT-NEXT:    mov x0, x17
; UNCHECKED-HINT-NEXT:    ret
;
; CHECKED-ELF-LABEL: test_resign_blend:
; CHECKED-ELF:       %bb.0:
; CHECKED-ELF-NEXT:    mov x17, x0
; CHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; CHECKED-ELF-NEXT:    autda x17, x1
; CHECKED-ELF-NEXT:    mov x16, x17
; CHECKED-ELF-NEXT:    xpacd x16
; CHECKED-ELF-NEXT:    cmp x16, x17
; CHECKED-ELF-NEXT:    b.eq [[L]]auth_success_0
; CHECKED-ELF-NEXT:    mov x17, x16
; CHECKED-ELF-NEXT:    b [[L]]resign_end_0
; CHECKED-ELF-NEXT:  Lauth_success_0:
; CHECKED-ELF-NEXT:    mov x16, x2
; CHECKED-ELF-NEXT:    movk x16, #56789, lsl #48
; CHECKED-ELF-NEXT:    pacdb x17, x16
; CHECKED-ELF-NEXT:  Lresign_end_0:
; CHECKED-ELF-NEXT:    mov x0, x17
; CHECKED-ELF-NEXT:    ret
;
; CHECKED-HINT-LABEL: test_resign_blend:
; CHECKED-HINT:       %bb.0:
; CHECKED-HINT-NEXT:    mov x17, x0
; CHECKED-HINT-NEXT:    mov x16, x1
; CHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; CHECKED-HINT-NEXT:    autia1716
; CHECKED-HINT-NEXT:    mov x16, x17
; CHECKED-HINT-NEXT:    xpacd x16
; CHECKED-HINT-NEXT:    cmp x16, x17
; CHECKED-HINT-NEXT:    b.eq [[L]]auth_success_0
; CHECKED-HINT-NEXT:    mov x17, x16
; CHECKED-HINT-NEXT:    b [[L]]resign_end_0
; CHECKED-HINT-NEXT:  Lauth_success_0:
; CHECKED-HINT-NEXT:    mov x16, x2
; CHECKED-HINT-NEXT:    movk x16, #56789, lsl #48
; CHECKED-HINT-NEXT:    pacib1716
; CHECKED-HINT-NEXT:  Lresign_end_0:
; CHECKED-HINT-NEXT:    mov x0, x17
; CHECKED-HINT-NEXT:    ret
;
; TRAP-ELF-LABEL: test_resign_blend:
; TRAP-ELF:       %bb.0:
; TRAP-ELF-NEXT:    mov x17, x0
; TRAP-ELF-NEXT:    movk x1, #12345, lsl #48
; TRAP-ELF-NEXT:    autda x17, x1
; TRAP-ELF-NEXT:    mov x16, x17
; TRAP-ELF-NEXT:    xpacd x16
; TRAP-ELF-NEXT:    cmp x16, x17
; TRAP-ELF-NEXT:    b.eq [[L]]auth_success_1
; TRAP-ELF-NEXT:    brk #0xc472
; TRAP-ELF-NEXT:  Lauth_success_1:
; TRAP-ELF-NEXT:    mov x16, x2
; TRAP-ELF-NEXT:    movk x16, #56789, lsl #48
; TRAP-ELF-NEXT:    pacdb x17, x16
; TRAP-ELF-NEXT:    mov x0, x17
; TRAP-ELF-NEXT:    ret
;
; TRAP-HINT-LABEL: test_resign_blend:
; TRAP-HINT:       %bb.0:
; TRAP-HINT-NEXT:    mov x17, x0
; TRAP-HINT-NEXT:    mov x16, x1
; TRAP-HINT-NEXT:    movk x16, #12345, lsl #48
; TRAP-HINT-NEXT:    autia1716
; TRAP-HINT-NEXT:    mov x16, x17
; TRAP-HINT-NEXT:    xpacd x16
; TRAP-HINT-NEXT:    cmp x16, x17
; TRAP-HINT-NEXT:    b.eq [[L]]auth_success_1
; TRAP-HINT-NEXT:    brk #0xc472
; TRAP-HINT-NEXT:  Lauth_success_1:
; TRAP-HINT-NEXT:    mov x16, x2
; TRAP-HINT-NEXT:    movk x16, #56789, lsl #48
; TRAP-HINT-NEXT:    pacib1716
; TRAP-HINT-NEXT:    mov x0, x17
; TRAP-HINT-NEXT:    ret
  %tmp0 = call i64 @llvm.ptrauth.blend(i64 %arg1, i64 12345)
  %tmp1 = call i64 @llvm.ptrauth.blend(i64 %arg2, i64 56789)
  %tmp2 = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %tmp0, i32 3, i64 %tmp1)
  ret i64 %tmp2
}

define i64 @test_resign_blend_and_const(i64 %arg, i64 %arg1) {
; UNCHECKED-ELF-LABEL: test_resign_blend_and_const:
; UNCHECKED-ELF:       %bb.0:
; UNCHECKED-ELF-NEXT:    mov x17, x0
; UNCHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; UNCHECKED-ELF-NEXT:    autda x17, x1
; UNCHECKED-ELF-NEXT:    mov x16, #56789
; UNCHECKED-ELF-NEXT:    pacdb x17, x16
; UNCHECKED-ELF-NEXT:    mov x0, x17
; UNCHECKED-ELF-NEXT:    ret
;
; UNCHECKED-HINT-LABEL: test_resign_blend_and_const:
; UNCHECKED-HINT:       %bb.0:
; UNCHECKED-HINT-NEXT:    mov x17, x0
; UNCHECKED-HINT-NEXT:    mov x16, x1
; UNCHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; UNCHECKED-HINT-NEXT:    autia1716
; UNCHECKED-HINT-NEXT:    mov x16, #56789
; UNCHECKED-HINT-NEXT:    pacib1716
; UNCHECKED-HINT-NEXT:    mov x0, x17
; UNCHECKED-HINT-NEXT:    ret
;
; CHECKED-ELF-LABEL: test_resign_blend_and_const:
; CHECKED-ELF:       %bb.0:
; CHECKED-ELF-NEXT:    mov x17, x0
; CHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; CHECKED-ELF-NEXT:    autda x17, x1
; CHECKED-ELF-NEXT:    mov x16, x17
; CHECKED-ELF-NEXT:    xpacd x16
; CHECKED-ELF-NEXT:    cmp x16, x17
; CHECKED-ELF-NEXT:    b.eq [[L]]auth_success_1
; CHECKED-ELF-NEXT:    mov x17, x16
; CHECKED-ELF-NEXT:    b [[L]]resign_end_1
; CHECKED-ELF-NEXT:  Lauth_success_1:
; CHECKED-ELF-NEXT:    mov x16, #56789
; CHECKED-ELF-NEXT:    pacdb x17, x16
; CHECKED-ELF-NEXT:  Lresign_end_1:
; CHECKED-ELF-NEXT:    mov x0, x17
; CHECKED-ELF-NEXT:    ret
;
; CHECKED-HINT-LABEL: test_resign_blend_and_const:
; CHECKED-HINT:       %bb.0:
; CHECKED-HINT-NEXT:    mov x17, x0
; CHECKED-HINT-NEXT:    mov x16, x1
; CHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; CHECKED-HINT-NEXT:    autia1716
; CHECKED-HINT-NEXT:    mov x16, x17
; CHECKED-HINT-NEXT:    xpacd x16
; CHECKED-HINT-NEXT:    cmp x16, x17
; CHECKED-HINT-NEXT:    b.eq [[L]]auth_success_1
; CHECKED-HINT-NEXT:    mov x17, x16
; CHECKED-HINT-NEXT:    b [[L]]resign_end_1
; CHECKED-HINT-NEXT:  Lauth_success_1:
; CHECKED-HINT-NEXT:    mov x16, #56789
; CHECKED-HINT-NEXT:    pacib1716
; CHECKED-HINT-NEXT:  Lresign_end_1:
; CHECKED-HINT-NEXT:    mov x0, x17
; CHECKED-HINT-NEXT:    ret
;
; TRAP-ELF-LABEL: test_resign_blend_and_const:
; TRAP-ELF:       %bb.0:
; TRAP-ELF-NEXT:    mov x17, x0
; TRAP-ELF-NEXT:    movk x1, #12345, lsl #48
; TRAP-ELF-NEXT:    autda x17, x1
; TRAP-ELF-NEXT:    mov x16, x17
; TRAP-ELF-NEXT:    xpacd x16
; TRAP-ELF-NEXT:    cmp x16, x17
; TRAP-ELF-NEXT:    b.eq [[L]]auth_success_2
; TRAP-ELF-NEXT:    brk #0xc472
; TRAP-ELF-NEXT:  Lauth_success_2:
; TRAP-ELF-NEXT:    mov x16, #56789
; TRAP-ELF-NEXT:    pacdb x17, x16
; TRAP-ELF-NEXT:    mov x0, x17
; TRAP-ELF-NEXT:    ret
;
; TRAP-HINT-LABEL: test_resign_blend_and_const:
; TRAP-HINT:       %bb.0:
; TRAP-HINT-NEXT:    mov x17, x0
; TRAP-HINT-NEXT:    mov x16, x1
; TRAP-HINT-NEXT:    movk x16, #12345, lsl #48
; TRAP-HINT-NEXT:    autia1716
; TRAP-HINT-NEXT:    mov x16, x17
; TRAP-HINT-NEXT:    xpacd x16
; TRAP-HINT-NEXT:    cmp x16, x17
; TRAP-HINT-NEXT:    b.eq [[L]]auth_success_2
; TRAP-HINT-NEXT:    brk #0xc472
; TRAP-HINT-NEXT:  Lauth_success_2:
; TRAP-HINT-NEXT:    mov x16, #56789
; TRAP-HINT-NEXT:    pacib1716
; TRAP-HINT-NEXT:    mov x0, x17
; TRAP-HINT-NEXT:    ret
  %tmp0 = call i64 @llvm.ptrauth.blend(i64 %arg1, i64 12345)
  %tmp1 = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %tmp0, i32 3, i64 56789)
  ret i64 %tmp1
}

define i64 @test_resign_blend_and_addr(i64 %arg, i64 %arg1, i64 %arg2) {
; UNCHECKED-ELF-LABEL: test_resign_blend_and_addr:
; UNCHECKED-ELF:       %bb.0:
; UNCHECKED-ELF-NEXT:    mov x17, x0
; UNCHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; UNCHECKED-ELF-NEXT:    autda x17, x1
; UNCHECKED-ELF-NEXT:    pacdb x17, x2
; UNCHECKED-ELF-NEXT:    mov x0, x17
; UNCHECKED-ELF-NEXT:    ret
;
; UNCHECKED-HINT-LABEL: test_resign_blend_and_addr:
; UNCHECKED-HINT:       %bb.0:
; UNCHECKED-HINT-NEXT:    mov x17, x0
; UNCHECKED-HINT-NEXT:    mov x16, x1
; UNCHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; UNCHECKED-HINT-NEXT:    autia1716
; UNCHECKED-HINT-NEXT:    mov x16, x2
; UNCHECKED-HINT-NEXT:    pacib1716
; UNCHECKED-HINT-NEXT:    mov x0, x17
; UNCHECKED-HINT-NEXT:    ret
;
; CHECKED-ELF-LABEL: test_resign_blend_and_addr:
; CHECKED-ELF:       %bb.0:
; CHECKED-ELF-NEXT:    mov x17, x0
; CHECKED-ELF-NEXT:    movk x1, #12345, lsl #48
; CHECKED-ELF-NEXT:    autda x17, x1
; CHECKED-ELF-NEXT:    mov x16, x17
; CHECKED-ELF-NEXT:    xpacd x16
; CHECKED-ELF-NEXT:    cmp x16, x17
; CHECKED-ELF-NEXT:    b.eq [[L]]auth_success_2
; CHECKED-ELF-NEXT:    mov x17, x16
; CHECKED-ELF-NEXT:    b [[L]]resign_end_2
; CHECKED-ELF-NEXT:  Lauth_success_2:
; CHECKED-ELF-NEXT:    pacdb x17, x2
; CHECKED-ELF-NEXT:  Lresign_end_2:
; CHECKED-ELF-NEXT:    mov x0, x17
; CHECKED-ELF-NEXT:    ret
;
; CHECKED-HINT-LABEL: test_resign_blend_and_addr:
; CHECKED-HINT:       %bb.0:
; CHECKED-HINT-NEXT:    mov x17, x0
; CHECKED-HINT-NEXT:    mov x16, x1
; CHECKED-HINT-NEXT:    movk x16, #12345, lsl #48
; CHECKED-HINT-NEXT:    autia1716
; CHECKED-HINT-NEXT:    mov x16, x17
; CHECKED-HINT-NEXT:    xpacd x16
; CHECKED-HINT-NEXT:    cmp x16, x17
; CHECKED-HINT-NEXT:    b.eq [[L]]auth_success_2
; CHECKED-HINT-NEXT:    mov x17, x16
; CHECKED-HINT-NEXT:    b [[L]]resign_end_2
; CHECKED-HINT-NEXT:  Lauth_success_2:
; CHECKED-HINT-NEXT:    mov x16, x2
; CHECKED-HINT-NEXT:    pacib1716
; CHECKED-HINT-NEXT:  Lresign_end_2:
; CHECKED-HINT-NEXT:    mov x0, x17
; CHECKED-HINT-NEXT:    ret
;
; TRAP-ELF-LABEL: test_resign_blend_and_addr:
; TRAP-ELF:       %bb.0:
; TRAP-ELF-NEXT:    mov x17, x0
; TRAP-ELF-NEXT:    movk x1, #12345, lsl #48
; TRAP-ELF-NEXT:    autda x17, x1
; TRAP-ELF-NEXT:    mov x16, x17
; TRAP-ELF-NEXT:    xpacd x16
; TRAP-ELF-NEXT:    cmp x16, x17
; TRAP-ELF-NEXT:    b.eq [[L]]auth_success_3
; TRAP-ELF-NEXT:    brk #0xc472
; TRAP-ELF-NEXT:  Lauth_success_3:
; TRAP-ELF-NEXT:    pacdb x17, x2
; TRAP-ELF-NEXT:    mov x0, x17
; TRAP-ELF-NEXT:    ret
;
; TRAP-HINT-LABEL: test_resign_blend_and_addr:
; TRAP-HINT:       %bb.0:
; TRAP-HINT-NEXT:    mov x17, x0
; TRAP-HINT-NEXT:    mov x16, x1
; TRAP-HINT-NEXT:    movk x16, #12345, lsl #48
; TRAP-HINT-NEXT:    autia1716
; TRAP-HINT-NEXT:    mov x16, x17
; TRAP-HINT-NEXT:    xpacd x16
; TRAP-HINT-NEXT:    cmp x16, x17
; TRAP-HINT-NEXT:    b.eq [[L]]auth_success_3
; TRAP-HINT-NEXT:    brk #0xc472
; TRAP-HINT-NEXT:  Lauth_success_3:
; TRAP-HINT-NEXT:    mov x16, x2
; TRAP-HINT-NEXT:    pacib1716
; TRAP-HINT-NEXT:    mov x0, x17
; TRAP-HINT-NEXT:    ret
  %tmp0 = call i64 @llvm.ptrauth.blend(i64 %arg1, i64 12345)
  %tmp1 = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %tmp0, i32 3, i64 %arg2)
  ret i64 %tmp1
}

define i64 @test_auth_too_large_discriminator(i64 %arg, i64 %arg1) {
; UNCHECKED-ELF-LABEL:     test_auth_too_large_discriminator:
; UNCHECKED-ELF:           %bb.0:
; UNCHECKED-ELF-NEXT:        mov w8, #65536
; UNCHECKED-ELF-NEXT:        bfi x1, x8, #48, #16
; UNCHECKED-ELF-NEXT:        autda x0, x1
; UNCHECKED-ELF-NEXT:        ret
;
; UNCHECKED-HINT-LABEL:     test_auth_too_large_discriminator:
; UNCHECKED-HINT:           %bb.0:
; UNCHECKED-HINT-NEXT:        mov w8, #65536
; UNCHECKED-HINT-NEXT:        mov x17, x0
; UNCHECKED-HINT-NEXT:        bfi x1, x8, #48, #16
; UNCHECKED-HINT-NEXT:        mov x16, x1
; UNCHECKED-HINT-NEXT:        autia1716
; UNCHECKED-HINT-NEXT:        mov x0, x17
; UNCHECKED-HINT-NEXT:        ret
;
; CHECKED-ELF-LABEL: test_auth_too_large_discriminator:
; CHECKED-ELF:           %bb.0:
; CHECKED-ELF-NEXT:        mov w8, #65536
; CHECKED-ELF-NEXT:        bfi x1, x8, #48, #16
; CHECKED-ELF-NEXT:        autda x0, x1
; CHECKED-ELF-NEXT:        ret
;
; CHECKED-HINT-LABEL: test_auth_too_large_discriminator:
; CHECKED-HINT:           %bb.0:
; CHECKED-HINT-NEXT:        mov w8, #65536
; CHECKED-HINT-NEXT:        mov x17, x0
; CHECKED-HINT-NEXT:        bfi x1, x8, #48, #16
; CHECKED-HINT-NEXT:        mov x16, x1
; CHECKED-HINT-NEXT:        autia1716
; CHECKED-HINT-NEXT:        mov x0, x17
; CHECKED-HINT-NEXT:        ret
;
; TRAP-ELF-LABEL: test_auth_too_large_discriminator:
; TRAP-ELF:           %bb.0:
; TRAP-ELF-NEXT:        mov w8, #65536
; TRAP-ELF-NEXT:        bfi x1, x8, #48, #16
; TRAP-ELF-NEXT:        autda x0, x1
; TRAP-ELF-NEXT:        mov x8, x0
; TRAP-ELF-NEXT:        xpacd x8
; TRAP-ELF-NEXT:        cmp x8, x0
; TRAP-ELF-NEXT:        b.eq [[L]]auth_success_4
; TRAP-ELF-NEXT:        brk #0xc472
; TRAP-ELF-NEXT:      Lauth_success_4:
; TRAP-ELF-NEXT:        ret
;
; TRAP-HINT-LABEL: test_auth_too_large_discriminator:
; TRAP-HINT:           %bb.0:
; TRAP-HINT-NEXT:        mov w8, #65536
; TRAP-HINT-NEXT:        mov x17, x0
; TRAP-HINT-NEXT:        bfi x1, x8, #48, #16
; TRAP-HINT-NEXT:        mov x16, x1
; TRAP-HINT-NEXT:        autia1716
; TRAP-HINT-NEXT:        mov x16, x17
; TRAP-HINT-NEXT:        xpacd x16
; TRAP-HINT-NEXT:        cmp x16, x17
; TRAP-HINT-NEXT:        b.eq [[L]]auth_success_4
; TRAP-HINT-NEXT:        brk #0xc472
; TRAP-HINT-NEXT:      Lauth_success_4:
; TRAP-HINT-NEXT:        mov x0, x17
; TRAP-HINT-NEXT:        ret
  %tmp0 = call i64 @llvm.ptrauth.blend(i64 %arg1, i64 65536)
  %tmp1 = call i64 @llvm.ptrauth.auth(i64 %arg, i32 2, i64 %tmp0)
  ret i64 %tmp1
}

declare i64 @llvm.ptrauth.auth(i64, i32, i64)
declare i64 @llvm.ptrauth.resign(i64, i32, i64, i32, i64)
declare i64 @llvm.ptrauth.blend(i64, i64)
