; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                  -verify-machineinstrs -global-isel=0 | \
; RUN:     FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth,+pauth-hint-only -verify-machineinstrs -global-isel=0 | \
; RUN:     FileCheck %s --check-prefix=HINT

; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                  -verify-machineinstrs -global-isel=1 \
; RUN-NOT:     -global-isel-abort=1 | FileCheck %s --check-prefix=CHECK
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth,+pauth-hint-only -verify-machineinstrs -global-isel=1 \
; RUN-NOT:     -global-isel-abort=1 | FileCheck %s --check-prefix=HINT

define i64 @test_strip_ia(i64 %arg) {
; CHECK-LABEL: test_strip_ia:
; CHECK:       %bb.0:
; CHECK-NEXT:    xpaci x0
; CHECK-NEXT:    ret
;
; HINT-LABEL: test_strip_ia:
; HINT: %bb.0:
; HINT-NEXT:    mov x16, x30
; HINT-NEXT:    mov x30, x0
; HINT-NEXT:    xpaclri
; HINT-NEXT:    mov x0, x30
; HINT-NEXT:    mov x30, x16
; HINT-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.strip(i64 %arg, i32 0)
  ret i64 %tmp
}

define i64 @test_strip_ib(i64 %arg) {
; CHECK-LABEL: test_strip_ib:
; CHECK:       %bb.0:
; CHECK-NEXT:    xpaci x0
; CHECK-NEXT:    ret
;
; HINT-LABEL: test_strip_ib:
; HINT:       %bb.0:
; HINT-NEXT:    mov x16, x30
; HINT-NEXT:    mov x30, x0
; HINT-NEXT:    xpaclri
; HINT-NEXT:    mov x0, x30
; HINT-NEXT:    mov x30, x16
; HINT-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.strip(i64 %arg, i32 1)
  ret i64 %tmp
}

define i64 @test_strip_da(i64 %arg) {
; CHECK-LABEL: test_strip_da:
; CHECK:       %bb.0:
; CHECK-NEXT:    xpacd x0
; CHECK-NEXT:    ret
;
; HINT-LABEL: test_strip_da:
; HINT:       %bb.0:
; HINT-NEXT:    mov x16, x30
; HINT-NEXT:    mov x30, x0
; HINT-NEXT:    xpaclri
; HINT-NEXT:    mov x0, x30
; HINT-NEXT:    mov x30, x16
; HINT-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.strip(i64 %arg, i32 2)
  ret i64 %tmp
}

define i64 @test_strip_db(i64 %arg) {
; CHECK-LABEL: test_strip_db:
; CHECK:       %bb.0:
; CHECK-NEXT:    xpacd x0
; CHECK-NEXT:    ret
;
; HINT-LABEL: test_strip_db:
; HINT:       %bb.0:
; HINT-NEXT:    mov x16, x30
; HINT-NEXT:    mov x30, x0
; HINT-NEXT:    xpaclri
; HINT-NEXT:    mov x0, x30
; HINT-NEXT:    mov x30, x16
; HINT-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.strip(i64 %arg, i32 3)
  ret i64 %tmp
}

declare i64 @llvm.ptrauth.strip(i64, i32)
