; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    \
; RUN-NOT:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefix=ELF-UNCHECKED
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefix=ELF-UNCHECKED

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    \
; RUN:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefix=HINT-UNCHECKED
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=none | FileCheck %s -DL=".L" --check-prefix=HINT-UNCHECKED

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    \
; RUN:    -verify-machineinstrs                                   | FileCheck %s -DL=".L" --check-prefix=ELF-CHECKED
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs                                   | FileCheck %s -DL=".L" --check-prefix=ELF-CHECKED

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    \
; RUN:    -verify-machineinstrs                                   | FileCheck %s -DL=".L" --check-prefix=HINT-CHECKED
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs                                   | FileCheck %s -DL=".L" --check-prefix=HINT-CHECKED

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel=0                    \
; RUN:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefix=ELF-TRAP
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth                         -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefix=ELF-TRAP

; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel=0                    \
; RUN:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefix=HINT-TRAP
; RUN-NOT: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -mattr=+pauth-hint-only -global-isel -global-isel-abort=1 \
; RUN-NOT:    -verify-machineinstrs -aarch64-ptrauth-auth-checks=trap | FileCheck %s -DL=".L" --check-prefix=HINT-TRAP

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"

define i64 @test_auth_ia(i64 %arg, i64 %arg1) {
; ELF-UNCHECKED-LABEL: test_auth_ia:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autia x17, x1
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_ia:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_ia:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autia x0, x1
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_ia:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_ia:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autia x0, x1
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_0
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_0:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_ia:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_0
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_0:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 0, i64 %arg1)
  ret i64 %tmp
}

define i64 @test_auth_ia_zero(i64 %arg) {
; ELF-UNCHECKED-LABEL: test_auth_ia_zero:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autiza x17
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_ia_zero:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_ia_zero:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autiza x0
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_ia_zero:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_ia_zero:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autiza x0
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_1
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_1:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_ia_zero:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_1
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_1:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 0, i64 0)
  ret i64 %tmp
}

define i64 @test_auth_ib(i64 %arg, i64 %arg1) {
; ELF-UNCHECKED-LABEL: test_auth_ib:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autib x17, x1
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_ib:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_ib:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autib x0, x1
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_ib:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_ib:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autib x0, x1
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_2
; ELF-TRAP-NEXT:    brk #0xc471
; ELF-TRAP-NEXT:  Lauth_success_2:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_ib:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_2
; HINT-TRAP-NEXT:    brk #0xc471
; HINT-TRAP-NEXT:  Lauth_success_2:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 1, i64 %arg1)
  ret i64 %tmp
}

define i64 @test_auth_ib_zero(i64 %arg) {
; ELF-UNCHECKED-LABEL: test_auth_ib_zero:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autizb x17
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_ib_zero:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_ib_zero:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autizb x0
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_ib_zero:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_ib_zero:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autizb x0
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_3
; ELF-TRAP-NEXT:    brk #0xc471
; ELF-TRAP-NEXT:  Lauth_success_3:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_ib_zero:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_3
; HINT-TRAP-NEXT:    brk #0xc471
; HINT-TRAP-NEXT:  Lauth_success_3:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 1, i64 0)
  ret i64 %tmp
}

define i64 @test_auth_da(i64 %arg, i64 %arg1) {
; ELF-UNCHECKED-LABEL: test_auth_da:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autda x17, x1
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_da:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_da:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autda x0, x1
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_da:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_da:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autda x0, x1
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpacd x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_4
; ELF-TRAP-NEXT:    brk #0xc472
; ELF-TRAP-NEXT:  Lauth_success_4:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_da:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_4
; HINT-TRAP-NEXT:    brk #0xc472
; HINT-TRAP-NEXT:  Lauth_success_4:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 2, i64 %arg1)
  ret i64 %tmp
}

define i64 @test_auth_da_zero(i64 %arg) {
; ELF-UNCHECKED-LABEL: test_auth_da_zero:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autdza x17
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_da_zero:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_da_zero:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autdza x0
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_da_zero:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_da_zero:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autdza x0
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpacd x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_5
; ELF-TRAP-NEXT:    brk #0xc472
; ELF-TRAP-NEXT:  Lauth_success_5:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_da_zero:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_5
; HINT-TRAP-NEXT:    brk #0xc472
; HINT-TRAP-NEXT:  Lauth_success_5:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 2, i64 0)
  ret i64 %tmp
}

define i64 @test_auth_db(i64 %arg, i64 %arg1) {
; ELF-UNCHECKED-LABEL: test_auth_db:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autdb x17, x1
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_db:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_db:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autdb x0, x1
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_db:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_db:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autdb x0, x1
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpacd x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_6
; ELF-TRAP-NEXT:    brk #0xc473
; ELF-TRAP-NEXT:  Lauth_success_6:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_db:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_6
; HINT-TRAP-NEXT:    brk #0xc473
; HINT-TRAP-NEXT:  Lauth_success_6:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 3, i64 %arg1)
  ret i64 %tmp
}

define i64 @test_auth_db_zero(i64 %arg) {
; ELF-UNCHECKED-LABEL: test_auth_db_zero:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autdzb x17
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_db_zero:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_db_zero:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autdzb x0
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_db_zero:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_db_zero:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autdzb x0
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpacd x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_7
; ELF-TRAP-NEXT:    brk #0xc473
; ELF-TRAP-NEXT:  Lauth_success_7:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_db_zero:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_7
; HINT-TRAP-NEXT:    brk #0xc473
; HINT-TRAP-NEXT:  Lauth_success_7:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 3, i64 0)
  ret i64 %tmp
}

;; Note that this might seem like a no-op but is actually a valid way to enforce
;; the validity of a signature.
define i64 @test_resign_ia_ia(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_ia_ia:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autia x17, x1
; ELF-UNCHECKED-NEXT:    pacia x17, x2
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_ia_ia:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x16, x2
; HINT-UNCHECKED-NEXT:    pacia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_ia_ia:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autia x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpaci x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_0
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_0
; ELF-CHECKED-NEXT:  Lauth_success_0:
; ELF-CHECKED-NEXT:    pacia x17, x2
; ELF-CHECKED-NEXT:  Lresign_end_0:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_ia_ia:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpaci x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_0
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_0
; HINT-CHECKED-NEXT:  Lauth_success_0:
; HINT-CHECKED-NEXT:    mov x16, x2
; HINT-CHECKED-NEXT:    pacia1716
; HINT-CHECKED-NEXT:  Lresign_end_0:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_ia_ia:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autia x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpaci x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_8
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_8:
; ELF-TRAP-NEXT:    pacia x17, x2
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_ia_ia:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_8
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_8:
; HINT-TRAP-NEXT:    mov x16, x2
; HINT-TRAP-NEXT:    pacia1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 0, i64 %arg1, i32 0, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_ib_ia(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_ib_ia:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autib x17, x1
; ELF-UNCHECKED-NEXT:    pacia x17, x2
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_ib_ia:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x16, x2
; HINT-UNCHECKED-NEXT:    pacia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_ib_ia:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autib x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpaci x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_1
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_1
; ELF-CHECKED-NEXT:  Lauth_success_1:
; ELF-CHECKED-NEXT:    pacia x17, x2
; ELF-CHECKED-NEXT:  Lresign_end_1:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_ib_ia:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpaci x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_1
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_1
; HINT-CHECKED-NEXT:  Lauth_success_1:
; HINT-CHECKED-NEXT:    mov x16, x2
; HINT-CHECKED-NEXT:    pacia1716
; HINT-CHECKED-NEXT:  Lresign_end_1:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_ib_ia:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autib x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpaci x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_9
; ELF-TRAP-NEXT:    brk #0xc471
; ELF-TRAP-NEXT:  Lauth_success_9:
; ELF-TRAP-NEXT:    pacia x17, x2
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_ib_ia:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_9
; HINT-TRAP-NEXT:    brk #0xc471
; HINT-TRAP-NEXT:  Lauth_success_9:
; HINT-TRAP-NEXT:    mov x16, x2
; HINT-TRAP-NEXT:    pacia1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 1, i64 %arg1, i32 0, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_da_ia(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_da_ia:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autda x17, x1
; ELF-UNCHECKED-NEXT:    pacia x17, x2
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_da_ia:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x16, x2
; HINT-UNCHECKED-NEXT:    pacia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_da_ia:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autda x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpacd x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_2
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_2
; ELF-CHECKED-NEXT:  Lauth_success_2:
; ELF-CHECKED-NEXT:    pacia x17, x2
; ELF-CHECKED-NEXT:  Lresign_end_2:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_da_ia:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpacd x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_2
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_2
; HINT-CHECKED-NEXT:  Lauth_success_2:
; HINT-CHECKED-NEXT:    mov x16, x2
; HINT-CHECKED-NEXT:    pacia1716
; HINT-CHECKED-NEXT:  Lresign_end_2:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_da_ia:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autda x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpacd x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_10
; ELF-TRAP-NEXT:    brk #0xc472
; ELF-TRAP-NEXT:  Lauth_success_10:
; ELF-TRAP-NEXT:    pacia x17, x2
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_da_ia:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_10
; HINT-TRAP-NEXT:    brk #0xc472
; HINT-TRAP-NEXT:  Lauth_success_10:
; HINT-TRAP-NEXT:    mov x16, x2
; HINT-TRAP-NEXT:    pacia1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %arg1, i32 0, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_db_da(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_db_da:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autdb x17, x1
; ELF-UNCHECKED-NEXT:    pacda x17, x2
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_db_da:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autib1716
; HINT-UNCHECKED-NEXT:    mov x16, x2
; HINT-UNCHECKED-NEXT:    pacia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_db_da:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autdb x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpacd x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_3
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_3
; ELF-CHECKED-NEXT:  Lauth_success_3:
; ELF-CHECKED-NEXT:    pacda x17, x2
; ELF-CHECKED-NEXT:  Lresign_end_3:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_db_da:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autib1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpacd x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_3
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_3
; HINT-CHECKED-NEXT:  Lauth_success_3:
; HINT-CHECKED-NEXT:    mov x16, x2
; HINT-CHECKED-NEXT:    pacia1716
; HINT-CHECKED-NEXT:  Lresign_end_3:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_db_da:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autdb x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpacd x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_11
; ELF-TRAP-NEXT:    brk #0xc473
; ELF-TRAP-NEXT:  Lauth_success_11:
; ELF-TRAP-NEXT:    pacda x17, x2
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_db_da:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autib1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_11
; HINT-TRAP-NEXT:    brk #0xc473
; HINT-TRAP-NEXT:  Lauth_success_11:
; HINT-TRAP-NEXT:    mov x16, x2
; HINT-TRAP-NEXT:    pacia1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 3, i64 %arg1, i32 2, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_iza_db(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_iza_db:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autiza x17
; ELF-UNCHECKED-NEXT:    pacdb x17, x2
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_iza_db:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x16, x2
; HINT-UNCHECKED-NEXT:    pacib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_iza_db:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autiza x17
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpaci x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_4
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_4
; ELF-CHECKED-NEXT:  Lauth_success_4:
; ELF-CHECKED-NEXT:    pacdb x17, x2
; ELF-CHECKED-NEXT:  Lresign_end_4:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_iza_db:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpaci x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_4
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_4
; HINT-CHECKED-NEXT:  Lauth_success_4:
; HINT-CHECKED-NEXT:    mov x16, x2
; HINT-CHECKED-NEXT:    pacib1716
; HINT-CHECKED-NEXT:  Lresign_end_4:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_iza_db:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autiza x17
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpaci x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_12
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_12:
; ELF-TRAP-NEXT:    pacdb x17, x2
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_iza_db:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_12
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_12:
; HINT-TRAP-NEXT:    mov x16, x2
; HINT-TRAP-NEXT:    pacib1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 0, i64 0, i32 3, i64 %arg2)
  ret i64 %tmp
}

define i64 @test_resign_da_dzb(i64 %arg, i64 %arg1, i64 %arg2) {
; ELF-UNCHECKED-LABEL: test_resign_da_dzb:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autda x17, x1
; ELF-UNCHECKED-NEXT:    pacdzb x17
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_da_dzb:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x16, xzr
; HINT-UNCHECKED-NEXT:    pacib1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_da_dzb:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autda x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpacd x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_5
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_5
; ELF-CHECKED-NEXT:  Lauth_success_5:
; ELF-CHECKED-NEXT:    pacdzb x17
; ELF-CHECKED-NEXT:  Lresign_end_5:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_da_dzb:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpacd x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_5
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_5
; HINT-CHECKED-NEXT:  Lauth_success_5:
; HINT-CHECKED-NEXT:    mov x16, xzr
; HINT-CHECKED-NEXT:    pacib1716
; HINT-CHECKED-NEXT:  Lresign_end_5:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_da_dzb:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autda x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpacd x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_13
; ELF-TRAP-NEXT:    brk #0xc472
; ELF-TRAP-NEXT:  Lauth_success_13:
; ELF-TRAP-NEXT:    pacdzb x17
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_da_dzb:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_13
; HINT-TRAP-NEXT:    brk #0xc472
; HINT-TRAP-NEXT:  Lauth_success_13:
; HINT-TRAP-NEXT:    mov x16, xzr
; HINT-TRAP-NEXT:    pacib1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %arg1, i32 3, i64 0)
  ret i64 %tmp
}

define i64 @test_auth_trap_attribute(i64 %arg, i64 %arg1) "ptrauth-auth-traps" {
; ELF-UNCHECKED-LABEL: test_auth_trap_attribute:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autia x17, x1
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_trap_attribute:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_trap_attribute:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    autia x0, x1
; ELF-CHECKED-NEXT:    mov x8, x0
; ELF-CHECKED-NEXT:    xpaci x8
; ELF-CHECKED-NEXT:    cmp x8, x0
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_6
; ELF-CHECKED-NEXT:    brk #0xc470
; ELF-CHECKED-NEXT:  Lauth_success_6:
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_trap_attribute:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpaci x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_6
; HINT-CHECKED-NEXT:    brk #0xc470
; HINT-CHECKED-NEXT:  Lauth_success_6:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_trap_attribute:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    autia x0, x1
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_14
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_14:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_trap_attribute:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_14
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_14:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 0, i64 %arg1)
  ret i64 %tmp
}

define i64 @test_auth_ia_constdisc(i64 %arg) {
; ELF-UNCHECKED-LABEL: test_auth_ia_constdisc:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    mov x16, #256
; ELF-UNCHECKED-NEXT:    autia x17, x16
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_auth_ia_constdisc:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, #256
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_auth_ia_constdisc:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x8, #256
; ELF-CHECKED-NEXT:    autia x0, x8
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_auth_ia_constdisc:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, #256
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_auth_ia_constdisc:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x8, #256
; ELF-TRAP-NEXT:    autia x0, x8
; ELF-TRAP-NEXT:    mov x8, x0
; ELF-TRAP-NEXT:    xpaci x8
; ELF-TRAP-NEXT:    cmp x8, x0
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_15
; ELF-TRAP-NEXT:    brk #0xc470
; ELF-TRAP-NEXT:  Lauth_success_15:
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_auth_ia_constdisc:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, #256
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpaci x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_15
; HINT-TRAP-NEXT:    brk #0xc470
; HINT-TRAP-NEXT:  Lauth_success_15:
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.auth(i64 %arg, i32 0, i64 256)
  ret i64 %tmp
}

define i64 @test_resign_da_constdisc(i64 %arg, i64 %arg1) {
; ELF-UNCHECKED-LABEL: test_resign_da_constdisc:
; ELF-UNCHECKED:       %bb.0:
; ELF-UNCHECKED-NEXT:    mov x17, x0
; ELF-UNCHECKED-NEXT:    autda x17, x1
; ELF-UNCHECKED-NEXT:    mov x16, #256
; ELF-UNCHECKED-NEXT:    pacda x17, x16
; ELF-UNCHECKED-NEXT:    mov x0, x17
; ELF-UNCHECKED-NEXT:    ret
;
; HINT-UNCHECKED-LABEL: test_resign_da_constdisc:
; HINT-UNCHECKED:       %bb.0:
; HINT-UNCHECKED-NEXT:    mov x17, x0
; HINT-UNCHECKED-NEXT:    mov x16, x1
; HINT-UNCHECKED-NEXT:    autia1716
; HINT-UNCHECKED-NEXT:    mov x16, #256
; HINT-UNCHECKED-NEXT:    pacia1716
; HINT-UNCHECKED-NEXT:    mov x0, x17
; HINT-UNCHECKED-NEXT:    ret
;
; ELF-CHECKED-LABEL: test_resign_da_constdisc:
; ELF-CHECKED:       %bb.0:
; ELF-CHECKED-NEXT:    mov x17, x0
; ELF-CHECKED-NEXT:    autda x17, x1
; ELF-CHECKED-NEXT:    mov x16, x17
; ELF-CHECKED-NEXT:    xpacd x16
; ELF-CHECKED-NEXT:    cmp x16, x17
; ELF-CHECKED-NEXT:    b.eq [[L]]auth_success_7
; ELF-CHECKED-NEXT:    mov x17, x16
; ELF-CHECKED-NEXT:    b [[L]]resign_end_6
; ELF-CHECKED-NEXT:  Lauth_success_7:
; ELF-CHECKED-NEXT:    mov x16, #256
; ELF-CHECKED-NEXT:    pacda x17, x16
; ELF-CHECKED-NEXT:  Lresign_end_6:
; ELF-CHECKED-NEXT:    mov x0, x17
; ELF-CHECKED-NEXT:    ret
;
; HINT-CHECKED-LABEL: test_resign_da_constdisc:
; HINT-CHECKED:       %bb.0:
; HINT-CHECKED-NEXT:    mov x17, x0
; HINT-CHECKED-NEXT:    mov x16, x1
; HINT-CHECKED-NEXT:    autia1716
; HINT-CHECKED-NEXT:    mov x16, x17
; HINT-CHECKED-NEXT:    xpacd x16
; HINT-CHECKED-NEXT:    cmp x16, x17
; HINT-CHECKED-NEXT:    b.eq [[L]]auth_success_7
; HINT-CHECKED-NEXT:    mov x17, x16
; HINT-CHECKED-NEXT:    b [[L]]resign_end_6
; HINT-CHECKED-NEXT:  Lauth_success_7:
; HINT-CHECKED-NEXT:    mov x16, #256
; HINT-CHECKED-NEXT:    pacia1716
; HINT-CHECKED-NEXT:  Lresign_end_6:
; HINT-CHECKED-NEXT:    mov x0, x17
; HINT-CHECKED-NEXT:    ret
;
; ELF-TRAP-LABEL: test_resign_da_constdisc:
; ELF-TRAP:       %bb.0:
; ELF-TRAP-NEXT:    mov x17, x0
; ELF-TRAP-NEXT:    autda x17, x1
; ELF-TRAP-NEXT:    mov x16, x17
; ELF-TRAP-NEXT:    xpacd x16
; ELF-TRAP-NEXT:    cmp x16, x17
; ELF-TRAP-NEXT:    b.eq [[L]]auth_success_16
; ELF-TRAP-NEXT:    brk #0xc472
; ELF-TRAP-NEXT:  Lauth_success_16:
; ELF-TRAP-NEXT:    mov x16, #256
; ELF-TRAP-NEXT:    pacda x17, x16
; ELF-TRAP-NEXT:    mov x0, x17
; ELF-TRAP-NEXT:    ret
;
; HINT-TRAP-LABEL: test_resign_da_constdisc:
; HINT-TRAP:       %bb.0:
; HINT-TRAP-NEXT:    mov x17, x0
; HINT-TRAP-NEXT:    mov x16, x1
; HINT-TRAP-NEXT:    autia1716
; HINT-TRAP-NEXT:    mov x16, x17
; HINT-TRAP-NEXT:    xpacd x16
; HINT-TRAP-NEXT:    cmp x16, x17
; HINT-TRAP-NEXT:    b.eq [[L]]auth_success_16
; HINT-TRAP-NEXT:    brk #0xc472
; HINT-TRAP-NEXT:  Lauth_success_16:
; HINT-TRAP-NEXT:    mov x16, #256
; HINT-TRAP-NEXT:    pacia1716
; HINT-TRAP-NEXT:    mov x0, x17
; HINT-TRAP-NEXT:    ret
  %tmp = call i64 @llvm.ptrauth.resign(i64 %arg, i32 2, i64 %arg1, i32 2, i64 256)
  ret i64 %tmp
}

declare i64 @llvm.ptrauth.auth(i64, i32, i64)
declare i64 @llvm.ptrauth.resign(i64, i32, i64, i32, i64)
